name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
      - real-world-app
  workflow_dispatch: ~

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      - name: "Install Production and Development Dependencies"
        run: "npm install"
      
      # This section makes as many pages as possible static.
      # If you don't want that, remove it and replace firebase:deploy:functions with firebase:deploy below
      # - name: "Export a Static Build"
      #   run: "npm run export"
      # - name: "Deploy Hosting"
      #   run: "npm run firebase:deploy:hosting"
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
      # On the other hand, if you only want your site to be static, remove this section
      - name: "Build for Production"
        run: "npm run prod"
        env:
          FIREBASE_BROWSER_CONFIG: ${{ secrets.FIREBASE_BROWSER_CONFIG }}
      - name: "Remove all but Production Dependencies"
        run: "npm install --only prod"
      - name: "Deploy"
        run: "npm run firebase:deploy"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
